version: '3'
services:
  java-app:
    image: tonyrudny/java-maven-app-private:1.1.7
    environment:
      - DB_USER=user
      - DB_PWD=pass
      - DB_SERVER=mysql
      - DB_NAME=my-app-db
    ports:
    - 8080:8080
    container_name: my-java-app
