- name: Copy docker compose 
  copy:
    src: docker-compose.yaml
    dest: /home/ec2-user/docker-compose.yaml
- name: Docker login
  docker_login:
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
- name: Start containers from compose
  community.docker.docker_compose_v2:
    project_src: /home/ec2-user
