---
- name: configure nginx server
  hosts: aws
  become: true
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
    # - name: copy nginx configuration
    #   copy:
    #     src: nginx.conf
    #     dest: /etc/nginx/nginx.conf
    - name: start nginx
      service:
        name: nginx
        state: started