---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: ~/.kube/15_ansible-kubeconfig
    - name: Deploy nginx app 
      kubernetes.core.k8s:
        src: ../nginx-config.yaml
        state: present
        kubeconfig: ~/.kube/15_ansible-kubeconfig
        namespace: my-app

