---
- name: Install Node.js
  hosts: aws
  become: true
  tasks:

    - name: Update apt cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: apt get
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - acl

    - name: Install Node.js and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Create new linux user for node app
  hosts: aws
  become: true
  vars_files:
    - vars
  tasks:
    - name: Create linux user
      user:
      # replace with your username
        name: "{{ node_user }}"
        comment: Node User
        group: admin
        password: "{{ node_user_password | password_hash('sha512') }}"
 
- name: Deploy NodeJS App
  hosts: aws
  become: True
  become_user: "{{ node_user }}"
  vars_files:
    - vars
  vars:
    user_home_dir: "/home/{{ node_user }}"

  tasks:

    - name: Unarchive app files
      unarchive:
        # /Users/tonyrudny/Developer/DevOps/techdegree-with-nana/15_ansible/node-app/nodeserver-0.0.0.tgz
        src: "{{ node_app_dir }}/node-app/nodeserver-{{app_version}}.tgz" 
        dest: "{{user_home_dir}}"

    - name: Install app dependencies
      npm:
        path: "{{user_home_dir}}/package"

    - name: Start the app
      command:
        chdir: "{{user_home_dir}}/package/src/server"
        cmd: node app.js
      async: 1000
      poll: 0
    
    - name: Wait for the app to start
      shell: ps aux | grep node
      register: result
    - debug: msg="{{ result.stdout_lines }}"